# Generated by Django 4.2.7 on 2023-11-25 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mypets',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Хозяин'),
        ),
        migrations.AddField(
            model_name='likes',
            name='ownerLikes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ownlikes', to=settings.AUTH_USER_MODEL, verbose_name='Хозяин'),
        ),
        migrations.AddField(
            model_name='likes',
            name='petsLikes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='pets.mypets', verbose_name='Лайк'),
        ),
    ]
