# Generated by Django 4.2.7 on 2023-12-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypets',
            name='breeds',
        ),
    ]
