# Generated by Django 4.2.7 on 2023-12-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_remove_mypets_breeds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posts',
        ),
    ]
